"""empty message

Revision ID: 6186d57a423b
Revises: ce0a3f865d4c
Create Date: 2022-05-30 22:48:20.067717

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6186d57a423b'
down_revision = 'ce0a3f865d4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artist_genres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.Column('genres', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['Artist.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('Artist', sa.Column('website', sa.String(length=500), nullable=True))
    op.add_column('Artist', sa.Column('seeking_venue', sa.Boolean(), nullable=True))
    op.add_column('Artist', sa.Column('seeking_description', sa.String(length=120), nullable=True))
    op.drop_column('Artist', 'genres')
    # ### end Alembic commands ###
    op.execute('UPDATE "Artist" SET seeking_venue = False WHERE seeking_venue IS NULL;')
    op.alter_column("Artist", 'seeking_venue', nullable=False)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('genres', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.drop_column('Artist', 'seeking_description')
    op.drop_column('Artist', 'seeking_venue')
    op.drop_column('Artist', 'website')
    op.drop_table('artist_genres')
    # ### end Alembic commands ###
