"""empty message

Revision ID: b704a3ae9c91
Revises: 684116cf5398
Create Date: 2022-06-02 23:02:44.223143

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b704a3ae9c91'
down_revision = '684116cf5398'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('available_start', sa.DateTime(), nullable=True))
    op.add_column('Artist', sa.Column('available_stop', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Artist', 'available_stop')
    op.drop_column('Artist', 'available_start')
    # ### end Alembic commands ###
