"""empty message

Revision ID: ce78619c96b0
Revises: 7a84c7a222af
Create Date: 2022-05-30 07:02:56.403227

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce78619c96b0'
down_revision = '7a84c7a222af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('genres', sa.String(length=200), nullable=True))
    op.add_column('Venue', sa.Column('website', sa.String(length=120), nullable=True))
    op.add_column('Venue', sa.Column('seeking_talent', sa.Boolean(), nullable=True))
    op.add_column('Venue', sa.Column('seeking_description', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###
    op.execute('UPDATE "Venue" SET seeking_talent = False WHERE seeking_talent IS NULL;')
    op.alter_column("Venue", 'seeking_talent', nullable=False)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'seeking_description')
    op.drop_column('Venue', 'seeking_talent')
    op.drop_column('Venue', 'website')
    op.drop_column('Venue', 'genres')
    # ### end Alembic commands ###
